#!/bin/bash
# Find shortwave g points. This script requires variables TOLERANCE to
# contain a list of heating-rate tolerances (in K d-1) for each g
# point to be used, APPLICATION to be ONE of "climate", "global-nwp"
# or "limited-area-nwp", and BAND_STRUCTURE to contain a list from
# "fsck", "wide" and "narrow". These variables may be provided either
# as environment variables, or should be set in a script provided as
# the first argument to this script that is sourced at the start.

# Source the configuration and checking header scripts
. config.h
. check_configuration.h

# Optional additional arguments
#EXTRA_ARGS="averaging_method=logarithmic"

# Create configuration file
if [ "$APP" = climate ]
then
    cat > config_find_g_points_sw_climate.cfg <<EOF
# THIS FILE WAS AUTOMATICALLY GENERATED BY $0
# Configuration file for generating g points for a radiation scheme to
# be used only for climate applications. Absorption spectra for each
# gas are reordered using present-day concentrations, setting the
# concentrations of all other gases also to the minimum over the range
# to be simulated. All well-mixed gases are combined into a single
# hybrid gas.

iprofile 0
averaging_method "transmission"
tolerance_tolerance 0.01 
flux_weight 0.0

gases composite h2o o3

\begin h2o
  # Water vapour in median present-day concentrations
  input ckdmip_mmm_sw_spectra_h2o_median.h5
  reordering_input sw_order_h2o.h5
  # Other gases in present-day concentrations, except ozone which uses
  # the minimum concentration
  background_input "ckdmip_mmm_sw_spectra_composite_minimum.h5
            ckdmip_mmm_sw_spectra_o3_minimum.h5"
\end h2o

\begin o3
  input ckdmip_mmm_sw_spectra_o3_median.h5
  reordering_input sw_order_o3.h5
  background_input "ckdmip_mmm_sw_spectra_composite_minimum.h5
            ckdmip_mmm_sw_spectra_h2o_minimum.h5"
\end o3

\begin composite
  input ckdmip_mmm_sw_spectra_composite_present.h5
  reordering_input sw_order_composite.h5
  background_input "ckdmip_mmm_sw_spectra_h2o_minimum.h5
            ckdmip_mmm_sw_spectra_o3_minimum.h5"
\end composite

EOF
elif [ "$APP" = nwp ]
then
    cat > config_find_g_points_sw_nwp.cfg <<EOF
# THIS FILE WAS AUTOMATICALLY GENERATED BY $0
# Configuration file for generating g points for a radiation scheme to
# be used only for NWP around the year 2020. Absorption spectra for
# each gas are reordered using present-day concentrations, setting the
# concentrations of all well-mixed gases also to present-day levels. All
# well-mixed gases ar combined into a single hybrid gas.

iprofile 0
averaging_method "transmission"
tolerance_tolerance 0.05
flux_weight 0.0

gases composite h2o o3

\begin h2o
  # Water vapour in median present-day concentrations
  input ckdmip_mmm_sw_spectra_h2o_median.h5
  reordering_input sw_order_h2o.h5
  # Other gases in present-day concentrations, except ozone which uses
  # the minimum concentration
  background_input "ckdmip_mmm_sw_spectra_composite_present.h5
            ckdmip_mmm_sw_spectra_o3_minimum.h5"
\end h2o

\begin o3
  input ckdmip_mmm_sw_spectra_o3_median.h5
  reordering_input sw_order_o3.h5
  background_input "ckdmip_mmm_sw_spectra_composite_present.h5
            ckdmip_mmm_sw_spectra_h2o_minimum.h5"
\end o3

\begin composite
  input ckdmip_mmm_sw_spectra_composite_present.h5
  reordering_input sw_order_composite.h5
  background_input "ckdmip_mmm_sw_spectra_h2o_minimum.h5
            ckdmip_mmm_sw_spectra_o3_minimum.h5"
\end composite

EOF
else
    ${BANNER_ERROR} 'APP "'$APP'" not understood'
    exit 1
fi

# Create output directory, if needed
mkdir -p ${WORK_SW_GPOINTS_DIR}

# Loop over each band structure and tolerance
for BANDSTRUCT in $BAND_STRUCTURE
do
    for TOL in $TOLERANCE
    do

	MODEL_CODE=${APPLICATION}_${BANDSTRUCT}_tol${TOL}${MODEL_CODE_SUFFIX}

	${BANNER} Finding g-points: $MODEL_CODE

	${FIND_G_POINTS} \
	    append_path="${MMM_SW_SPECTRA_DIR}:${WORK_SW_SPECTRA_DIR}:${WORK_SW_ORDER_DIR}" \
	    ssi=$MMM_SW_SSI \
	    heating_rate_tolerance=${TOL} \
	    min_pressure=${MIN_PRESSURE} \
	    h2o.reordering_input=sw_order_${BANDSTRUCT}_h2o.h5 \
	    o3.reordering_input=sw_order_${BANDSTRUCT}_o3.h5 \
	    composite.reordering_input=sw_order_${BANDSTRUCT}_composite.h5 \
	    output=${WORK_SW_GPOINTS_DIR}/sw_gpoints_${MODEL_CODE}.h5 \
	    $EXTRA_ARGS config_find_g_points_sw_${APP}.cfg \
	    | tee ${WORK_SW_GPOINTS_DIR}/sw_gpoints_${MODEL_CODE}.log
    done
done
